easydata/urls.py
# -*- coding: utf-8 -*-

#------------------------------------------------------------------------------
#    EasyData/Django: an app to publish your django projects data using
#                     vocabularies.
#    Copyright (C) 2013  Jose Manuel Llerena Carmona
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

"""
En este fichero se encuentran todas las urls definidas en la aplicacion
EasyData junto con las vistas que tienen asociadas.
"""

from django.conf.urls.defaults import *


urlpatterns = patterns('easydata.views',
    # Plantillas de EasyData
    (r'^$', 'information.welcome'),
    (r'^information/help/models/$', 'information.info_models'),
    (r'^information/help/entities/$', 'information.info_entities'),
    (r'^information/help/templatetags/$', 'information.info_templatetags'),
    (r'^logout/$', 'sesiones.disconnect'),
    (r'^namespace/listado/$', 'namespace.listado_namespaces'),
    (r'^namespace/nuevo/$', 'namespace.vista_carga_namespace'),
    (r'^namespace/editar/(?P<id>\d+)/$', 'namespace.editar_namespace'),
    (r'^namespace/eliminar/(?P<id>\d+)/$', 'namespace.eliminar_namespace'),
    (r'^modelos/visibility/(?P<aplicacion>[a-zA-Z_][0-9a-zA-Z_]*)/$',
     'modelo.configure_visibility_models'),
    (r'^modelos/visibility/$', 'modelo.select_visibility_app'),
    (r'^namespace/map/models/$', 'map.mapea_modelo'),
    (r'^namespace/map/graphic/$', 'map.create_configuration_graph'),
    (r'^namespace/entidades/$', 'map.devuelve_entidades'),
    (r'^namespace/propiedades/namespace/$',
     'map.devuelve_propiedades_namespace'),
    (r'^namespace/propiedades/default/$', 'map.devuelve_propiedades_default'),
    (r'^namespace/map/(?P<id>\d+)/properties/$', 'map.mapea_fields'),
    #Url para publicar los datos de una instancia concreta
    (r'^publish/instance/(?P<aplicacion>[a-zA-Z_][0-9a-zA-Z_]*)/' +
     '(?P<tipo>[0-9a-zA-Z]+)-(?P<modelo>[a-zA-Z_][0-9a-zA-Z_]*)/' +
     '(?P<clave>.*).(?P<format>(xml|nt|ttl))$', 'publish.publish_model'),
    #Url para publicar todas las instancias de un modelo
    (r'^publish/model/(?P<aplicacion>[a-zA-Z_][0-9a-zA-Z_]*)/' +
     '(?P<tipo>[0-9a-zA-Z]*)-(?P<modelo>[a-zA-Z_][0-9a-zA-Z_]*).' +
     '(?P<format>(xml|nt|ttl))$', 'publish.publish_model', {'clave': None}),
    #Url para publicar los datos de un tipo
    (r'^publish/type/(?P<names>[a-zA-Z][0-9a-zA-Z]*)/(?P<tipo>[0-9a-zA-Z]*).' +
     '(?P<format>(xml|nt|ttl))$', 'publish.publish_type'),
)

easydata/models/namespace.py
# -*- coding: utf-8 -*-

#------------------------------------------------------------------------------
#    EasyData/Django: an app to publish your django projects data using
#                     vocabularies.
#    Copyright (C) 2013  Jose Manuel Llerena Carmona
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

"""
Este modelo se encarga de almacenar la informacion relativa a las diferentes
namespaces que se podran almacenar en la aplicacion
"""

from django.contrib import admin
from django.db import models
from django.core.validators import RegexValidator
from django.utils.translation import ugettext as _


class NameSpace(models.Model):
    """
    Este modelo representa a los namespaces u ontologias que se cargaran en la
    aplicacion para realizar los mapeos
    """
    namespace = models.CharField(max_length=40,
                                 unique=True)
    """es el nombre del namespace"""

    short_name = models.CharField(
                 max_length=15,
                 unique=True,
                 validators=[RegexValidator(r'^[a-zA-Z][0-9a-zA-Z]*$',
                             _('Only alphanumeric characters are allowed.'))])
    """
    Es un nombre corto para el namespace que se usara en la publicacion de
    datos
    """

    formatos = (
        ('R', 'RDF/XML'),
        ('N', 'Ntriples'),
    )
    """son los formatos disponibles para la carga de namespaces"""

    url = models.URLField()
    """es la url donde se encuentra el namespace"""

    def __unicode__(self):
        return self.namespace

    def get_url(self):
        """devuelve la url del namespace"""
        return self.url

    def get_type(self):
        """devuelve el nombre corto del namespace"""
        return self.short_name

    class Meta:
        """Metadatos del modelo"""
        app_label = 'easydata'


class NameSpaceAdmin(admin.ModelAdmin):
    """Clase para registar en el admin de Django"""
    list_display = ['namespace', 'url', 'short_name']
    search_fields = ['namespace', 'url', 'short_name']


## Register in django.

admin.site.register(NameSpace, NameSpaceAdmin)

easydata/forms/forms/d2rqform.py
# -*- coding: utf-8 -*-

#------------------------------------------------------------------------------
#    EasyData/Django: an app to publish your django projects data using
#                     vocabularies.
#    Copyright (C) 2013  Jose Manuel Llerena Carmona
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

"""
Este modulo implementa el formulario para captar ficheros d2rq y modificarlos
mismos con la configuracion de la aplicacion
"""

from django import forms

__author__ = 'llerena'


class D2RqForm(forms.Form):
    """
    Este formulario se utiliza para captar un fichero del tipo D2Rq de tal
    forma que se modifique esta añadiendosele el etiquetado configurado en la
    aplicacion
    """
    archivo = forms.FileField(required=True)

easydata/views/namespace.py
# -*- coding: utf-8 -*-

#------------------------------------------------------------------------------
#    EasyData/Django: an app to publish your django projects data using
#                     vocabularies.
#    Copyright (C) 2013  Jose Manuel Llerena Carmona
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

"""
En este modulo se almacenan las vistas que gestionan los namespaces, tanto como
el listado, alta de nuevo namespaces, editar un namespace existente y la
eliminacion de los namespaces
"""

from django.shortcuts import render_to_response, redirect
from django.template import RequestContext
from django.contrib import messages
from django.db import transaction
from django.utils.translation import ugettext as _

from easydata.models import NameSpace
from easydata.forms import NewNamespaceForm, EditNamespaceForm
from easydata.parsing.parserfactory import parser_factory
from easydata.decorators.decorators import easydata_super_member

import urllib2

__author__ = 'llerena'


@easydata_super_member
def listado_namespaces(request):
    """
    This view show all the namespaces loaded into the application
    :param request: the request of the view
    :return: render the view
    """

    #Obtengo la lista de paises existentes en la base de datos
    lista_names = NameSpace.objects.all()
    lista_names = lista_names.extra(select={'lower_name': 'lower(namespace)'})
    lista_names = lista_names.order_by('lower_name')
    #listaNames = listaNames.order_by('namespace')

    #Renderizo la plantilla con el listado de paises
    return render_to_response('easydata/namespace/list.html',
                              {'datos': lista_names, },
                              context_instance=RequestContext(request))


@easydata_super_member
@transaction.commit_on_success
def vista_carga_namespace(request):
    """
    This view shows a form to load a new namespace into the application.
    :param request: the request of the view
    :return: render the form
    """

    #Si hay datos en el POST, valido el formulario y creo el nuevo namespace
    if request.POST:
        form = NewNamespaceForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            try:
                if form.cleaned_data["url"] != '':
                    fich = form.cleaned_data["url"]
                else:
                    fich = form.cleaned_data["archivo"]

                parser = parser_factory(fich, form.cleaned_data["formato"],
                                        form.instance)

                parser.parse()
                parser.register()

                mensaje1 = _("The namespace was created successfully.")
                mensaje2 = _("The namespace has ")
                mensaje2 += str(form.instance.entidades.all().count())
                mensaje2 += _(" entities and ")
                mensaje2 += str(form.instance.propiedades.all().count())
                mensaje2 += _(" properties")

                messages.info(request, mensaje1)
                messages.info(request, mensaje2)

                return redirect('easydata.views.namespace.listado_namespaces')
            except Exception:
                form.instance.delete()
                messages.info(request, _("There was an error, and the \
namespace couldn't be created"))
        else:
            messages.info(request, _("There are errors in the form, please \
check it and send the form to create the namespace"))
    else:
        form = NewNamespaceForm()

    #Renderizo la plantilla con el formulario
    return render_to_response('easydata/namespace/new.html',
                              {'form': form, },
                              context_instance=RequestContext(request))


@easydata_super_member
def editar_namespace(request, id):
    """
    This view shows a form to edit the info of a namespace, and reload the
    entities and properties
    :param request: the request of the view
    :param id: the primary key of the namespace
    :return: render the form
    """
    try:
        name = NameSpace.objects.get(id=id)
    except Exception:
        return redirect('easydata.views.namespace.listado_namespaces')

    #Obtengo la lista de paises existentes en la base de datos
    if request.POST:
        form = EditNamespaceForm(request.POST, request.FILES, instance=name)

        if form.is_valid():
            form.save()
            try:
                fich = None
                if form.cleaned_data["url"] != '':
                    fich = form.cleaned_data["url"]
                elif form.cleaned_data["archivo"]:
                    fich = form.cleaned_data["archivo"]

                if not fich is None:
                    parser = parser_factory(fich, form.cleaned_data["formato"],
                                            form.instance)

                    parser.parse()
                    parser.update()

                mensaje1 = _("The namespace was updated successfully.")
                mensaje2 = _("The namespace has ")
                mensaje2 += str(form.instance.entidades.all().count())
                mensaje2 += _(" entities and ")
                mensaje2 += str(form.instance.propiedades.all().count())
                mensaje2 += _(" properties")

                messages.info(request, mensaje1)
                messages.info(request, mensaje2)
                return redirect('easydata.views.namespace.listado_namespaces')
            except Exception:
                messages.info(request, _("There was an error, and the \
namespace couldn't be updated"))
        else:
            messages.info(request, _("There are errors in the form, please \
check it and send the form to update the namespace"))

    else:
        form = EditNamespaceForm(instance=name)

    #Renderizo la plantilla con el formulario
    return render_to_response('easydata/namespace/edit.html',
                              {'form': form, },
                              context_instance=RequestContext(request))


@easydata_super_member
def eliminar_namespace(request, id):
    """
    This view delete a concreta namespace, and all the entities and properties,
    and the relations between the models and fields
    :param request: the request of the view
    :param id: the primary key of the namespace
    :return: None
    """
    try:
        name = NameSpace.objects.get(id=id)
    except Exception:
        return redirect('easydata.views.namespace.listado_namespaces')

    # Obtengo todas las entidades y propiedades del
    # namespace para eliminarlas tambien
    entities = name.entidades.all()
    props = name.propiedades.all()

    #Elimino todo
    props.delete()
    entities.delete()
    name.delete()

    #Create the message
    messages.info(request, _('The namespace was deleted'))

    #Redirijo al listado de namespaces
    return redirect('easydata.views.namespace.listado_namespaces')

easydata/templates/easydata/namespace/edit.html
{% extends "easydata/index.html" %}

{% load url from future %}
{% load i18n %}

{% block menu-superior %}
<li><a href="{% url "easydata.views.information.welcome" %}">{% trans "Home" %}</a></li>
<li class="active"><a href="{% url "easydata.views.namespace.listado_namespaces" %}">{% trans "Namespace" %}</a></li>
<li><a href="{% url "easydata.views.modelo.select_visibility_app" %}">{% trans "Visibility" %}</a></li>
<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">
    {% trans "Mapping" %}
    <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
        <li class="dropdown"><a href="{% url "easydata.views.map.mapea_modelo" %}">{% trans "Configure Mapping" %}</a></li>
        <li class="dropdown"><a href="{% url "easydata.views.map.create_configuration_graph" %}">{% trans "Generate Graph" %}</a></li>
    </ul>
</li>
<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">
    {% trans "Help" %}
    <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
        <li class="dropdown"><a href="{% url "easydata.views.information.info_models" %}">{% trans "Configured Models" %}</a></li>
        <li class="dropdown"><a href="{% url "easydata.views.information.info_entities" %}">{% trans "Related Entities" %}</a></li>
        <li class="dropdown"><a href="{% url "easydata.views.information.info_templatetags" %}">{% trans "Use in templates" %}</a></li>
    </ul>
</li>
{% endblock %}

{% block contenido-plantilla %}
    <h2>{% trans "Edit Namespace" %} - {{ form.instance.namespace }}</h2>

    <p>{% blocktrans with nombre_name=form.instance.namespace %}You are going to edit the existing {{ nombre_name }} namespace. You can edit the namespace's name and short_name and if you want to update the namespace specification, you can provide a file with the namespace specification to add the new entities and properties and construct the new existing relations.{% endblocktrans %}</p>

    <form role="form" method="POST" enctype="multipart/form-data">
        <fieldset>
            {% csrf_token %}
            <div class="form-group">
                <div class="row">
                    <div class="col-lg-6 {% if form.namespace.errors %}has-error{% endif %}">
                    <label for="id_namespace">{{ form.namespace.label }}</label>
                    {{ form.namespace }}
                    {% if form.namespace.errors %}<span class="help-block">{{ form.namespace.errors }}</span>{% endif %}
                    </div>
                    <div class="col-lg-6 {% if form.short_name.errors %}has-error{% endif %}">
                    <label for="id_short_name">{{ form.short_name.label }}</label>
                    {{ form.short_name }}
                    {% if form.short_name.errors %}<span class="help-block">{{ form.short_name.errors }}</span>{% endif %}
                    </div>
                </div>
            </div>
            <h3>{% trans "Update the entities and properties" %}</h3>
            <div class="form-group">
                <div class="row">
                    <div class="col-lg-2 {% if form.formato.errors %}has-error{% endif %}">
                    <label for="id_formato">{{ form.formato.label }}</label>
                    {{ form.formato }}
                    {% if form.formato.errors %}<span class="help-block">{{ form.formato.errors }}</span>{% endif %}
                    </div>
                    <div class="col-lg-10 {% if form.url.errors %}has-error{% endif %}">
                    <label for="id_url">{{ form.url.label }}</label>
                    {{ form.url }}
                    {% if form.url.errors %}<span class="help-block">{{ form.url.errors }}</span>{% endif %}
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-lg-12">
                    <label for="id_archivo">{{ form.archivo.label }}</label>
                    {{ form.archivo }}
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-lg-6">
                        <a type="submit" href="{% url "easydata.views.namespace.listado_namespaces" %}" class="btn btn-danger btn-sm">{% trans "Back" %}</a>
                        <button type="submit" class="btn btn-primary btn-sm">{% trans "Edit namespace" %}</button>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
{% endblock %}

easydata/templates/easydata/namespace/list.html
{% extends "easydata/index.html" %}

{% load url from future %}
{% load i18n %}

{% block menu-superior %}
<li><a href="{% url "easydata.views.information.welcome" %}">{% trans "Home" %}</a></li>
<li class="active"><a href="{% url "easydata.views.namespace.listado_namespaces" %}">{% trans "Namespace" %}</a></li>
<li><a href="{% url "easydata.views.modelo.select_visibility_app" %}">{% trans "Visibility" %}</a></li>
<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">
    {% trans "Mapping" %}
    <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
        <li class="dropdown"><a href="{% url "easydata.views.map.mapea_modelo" %}">{% trans "Configure Mapping" %}</a></li>
        <li class="dropdown"><a href="{% url "easydata.views.map.create_configuration_graph" %}">{% trans "Generate Graph" %}</a></li>
    </ul>
</li>
<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">
    {% trans "Help" %}
    <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
        <li class="dropdown"><a href="{% url "easydata.views.information.info_models" %}">{% trans "Configured Models" %}</a></li>
        <li class="dropdown"><a href="{% url "easydata.views.information.info_entities" %}">{% trans "Related Entities" %}</a></li>
        <li class="dropdown"><a href="{% url "easydata.views.information.info_templatetags" %}">{% trans "Use in templates" %}</a></li>
    </ul>
</li>
{% endblock %}

{% block contenido-plantilla %}
	<h2>{% trans "List of Namespaces" %}</h2>

    <p>{% blocktrans %}Below you can see a full list with all your namespaces loaded into the application. In this section, you can add, edit or delete the namespaces. To add a new namespace, you have to provide the name, short name, and a file in the allowed formats with the specifications of the namespace. On the other hand, if you want to edit a namespace, you can change the name or short name, and optionaly update the namespace specification, providing a file with updated specification. Be careful before delete a namespace, because if you delete a namespace, all the configurations made using that namespace will be deleted and the changes can't be undone.{% endblocktrans %}</p>
    
    <table class="table table-condensed">
    	<thead>
    		<tr>
    			<th>{% trans "Namespace Name" %}</th>
    			<th>{% trans "Edit Namespace" %}</th>
    			<th>{% trans "Delete Namespace" %}</th>
    		</tr>
    	</thead>
    	<tbody>
	    {% for name in datos %}
	    	<tr>
	        	<th>{{name.namespace}}</th>
	        	<td><a class="btn btn-primary btn-xs" href="{% url "easydata.views.namespace.editar_namespace" name.id %}">{% trans "Edit Namespace" %}</a></td>
	        	<td><a class="btn btn-danger btn-xs" href="{% url "easydata.views.namespace.eliminar_namespace" name.id %}" onclick="return confirm('{% trans "Are you sure that you want to delete the namespace?" %}');">{% trans "Delete Namespace" %}</a></td>
	        </tr>
	    {% empty %}
	    	<tr>
	        	<td colspan="3">{% trans "Sorry, there are not nampesaces loaded" %}</td>
	        </tr>
	    {% endfor %}
	    <tr>
	    	<td colspan="3">
	    		<a type="button" class="btn btn-primary btn-sm" href="{% url "easydata.views.namespace.vista_carga_namespace" %}">{% trans "New Namespace" %}</a>
	    	</td>
	    </tr>
    	</tbody>
    </table>
{% endblock %}

easydata/templates/easydata/namespace/new.html
{% extends "easydata/index.html" %}

{% load url from future %}
{% load i18n %}

{% block menu-superior %}
<li><a href="{% url "easydata.views.information.welcome" %}">{% trans "Home" %}</a></li>
<li class="active"><a href="{% url "easydata.views.namespace.listado_namespaces" %}">{% trans "Namespace" %}</a></li>
<li><a href="{% url "easydata.views.modelo.select_visibility_app" %}">{% trans "Visibility" %}</a></li>
<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">
    {% trans "Mapping" %}
    <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
        <li class="dropdown"><a href="{% url "easydata.views.map.mapea_modelo" %}">{% trans "Configure Mapping" %}</a></li>
        <li class="dropdown"><a href="{% url "easydata.views.map.create_configuration_graph" %}">{% trans "Generate Graph" %}</a></li>
    </ul>
</li>
<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">
    {% trans "Help" %}
    <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
        <li class="dropdown"><a href="{% url "easydata.views.information.info_models" %}">{% trans "Configured Models" %}</a></li>
        <li class="dropdown"><a href="{% url "easydata.views.information.info_entities" %}">{% trans "Related Entities" %}</a></li>
        <li class="dropdown"><a href="{% url "easydata.views.information.info_templatetags" %}">{% trans "Use in templates" %}</a></li>
    </ul>
</li>
{% endblock %}

{% block contenido-plantilla %}
    <h2>{% trans "Create new namespace" %}</h2>
    <p>
    {% blocktrans %}You are going to create a new namespace. To do this, you have to provide the following data:{% endblocktrans %}
    </p>
    <ul>
        <li>{% blocktrans %}Namespace: is the name that you are going to use to identify the namespace into the application.{% endblocktrans %}</li>
        <li>{% blocktrans %}Short name: is the name that will be used to identify the namespace in the data publication.{% endblocktrans %}</li>
        <li>{% blocktrans %}File or URL: you have to provide a file or a URL (only one of this), where the application can load the namespace specification.{% endblocktrans %}</li>
    </ul>

    <form role="form" method="POST" enctype="multipart/form-data">
        <fieldset>
            {% csrf_token %}
            <div class="form-group">
                <div class="row">
                    <div class="col-lg-6 {% if form.namespace.errors %}has-error{% endif %}">
                    <label for="id_namespace">{{ form.namespace.label }}</label>
                    {{ form.namespace }}
                    {% if form.namespace.errors %}<span class="help-block">{{ form.namespace.errors }}</span>{% endif %}
                    </div>
                    <div class="col-lg-6 {% if form.short_name.errors %}has-error{% endif %}">
                    <label for="id_short_name">{{ form.short_name.label }}</label>
                    {{ form.short_name }}
                    {% if form.short_name.errors %}<span class="help-block">{{ form.short_name.errors }}</span>{% endif %}
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-lg-2 {% if form.formato.errors %}has-error{% endif %}">
                    <label for="id_formato">{{ form.formato.label }}</label>
                    {{ form.formato }}
                    {% if form.formato.errors %}<span class="help-block">{{ form.formato.errors }}</span>{% endif %}
                    </div>
                    <div class="col-lg-10 {% if form.url.errors %}has-error{% endif %}">
                    <label for="id_url">{{ form.url.label }}</label>
                    {{ form.url }}
                    {% if form.url.errors %}<span class="help-block">{{ form.url.errors }}</span>{% endif %}
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-lg-12">
                    <label for="id_archivo">{{ form.archivo.label }}</label>
                    {{ form.archivo }}
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-lg-6">
                        <a type="submit" href="{% url "easydata.views.namespace.listado_namespaces" %}" class="btn btn-danger btn-sm">{% trans "Back" %}</a>
                        <button type="submit" class="btn btn-primary btn-sm">{% trans "Create Namespace" %}</button>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
{% endblock %}